#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const files = {
  SKILL_TEXT: join(root, "content", "SKILL_agency_first_hiring.md"),
  REFERENCE_TEXT: join(root, "content", "REFERENCE_agency_first_hiring.md"),
  RUBRIC_TEMPLATE: join(root, "content", "templates", "agency-rubric.md"),
  PROBES_TEMPLATE: join(root, "content", "templates", "agency-interview-questions.md"),
};

const loaded = {};
for (const [name, path] of Object.entries(files)) {
  if (!existsSync(path)) {
    console.error(`Missing ${path}`);
    process.exit(1);
  }
  loaded[name] = readFileSync(path, "utf8");
}

const lines = ["// AUTO-GENERATED by scripts/sync-content.mjs.", ""];
for (const [name, text] of Object.entries(loaded)) {
  lines.push(`export const ${name}: string = ${JSON.stringify(text)};`);
  lines.push("");
}
writeFileSync(join(root, "src", "content.ts"), lines.join("\n"), "utf8");

const total = Object.values(loaded).reduce((s, t) => s + t.length, 0);
console.log(`Wrote src/content.ts (${Object.keys(loaded).length} files, ${total} chars).`);
